import { GameData } from '../models';
import { Dice } from '../utils/rollDie';

export const data: GameData = {
    armors: [
        {
            name: 'Fur armor',
            description: ' -d2 damage, tier 1',
            tags: ['armor', 'light-armor'],
            exp: false,
            maxTier: 1,
            dice: Dice.d2,
            roll: 2,
            value: 20,
        },
        {
            name: 'Padded cloth armor',
            description: ' -d2 damage, tier 1',
            tags: ['armor', 'light-armor'],
            exp: false,
            maxTier: 1,
            roll: 2,
            dice: Dice.d2,
            value: 20,
        },
        {
            name: 'Leather armor',
            description: ' -d2 damage, tier 1',
            tags: ['armor', 'light-armor'],
            exp: false,
            maxTier: 1,
            roll: 2,
            dice: Dice.d2,
            value: 20,
        },
        {
            name: 'Scale armor',
            description:
                ' -d4 damage, tier 2, DR +2 on Agility tests including defence',
            tags: ['armor', 'medium-armor', 'metal'],
            exp: false,
            maxTier: 2,
            roll: 3,
            dice: Dice.d4,
            value: 100,
        },
        {
            name: 'Mail armor',
            description:
                ' -d4 damage, tier 2, DR +2 on Agility tests including defence',
            tags: ['armor', 'medium-armor', 'metal'],
            exp: false,
            maxTier: 2,
            roll: 3,
            dice: Dice.d4,
            value: 100,
        },
        {
            name: 'Splint armor',
            description:
                ' -d6 damage, tier 3, DR +4 on Agility tests, defence is DR +2',
            tags: ['armor', 'heavy-armor', 'metal'],
            exp: false,
            maxTier: 3,
            roll: 4,
            dice: Dice.d6,
            value: 200,
        },
        {
            name: 'Plate armor',
            description:
                ' -d6 damage, tier 3, DR +4 on Agility tests, defence is DR +2',
            tags: ['armor', 'heavy-armor', 'metal'],
            exp: false,
            maxTier: 3,
            roll: 4,
            dice: Dice.d6,
            value: 200,
        },
    ],
    weapons: [
        {
            name: 'Femur',
            description: 'd4 damage',
            tags: ['weapon', 'melee'],
            dice: Dice.d4,
            roll: 1,
            exp: false,
            value: 0,
        },
        {
            name: 'Staff',
            description: ' d4 damage',
            tags: ['weapon', 'melee'],
            dice: Dice.d4,
            roll: 2,
            exp: false,
            value: 5,
        },
        {
            name: 'Whip',
            description: ' d2 damage',
            tags: ['weapon', 'melee'],
            dice: Dice.d2,
            exp: false,
            value: 5,
        },
        {
            name: 'Shortsword',
            description: ' d4 damage',
            tags: ['weapon', 'melee'],
            dice: Dice.d4,
            exp: false,
            roll: 3,
            value: 20,
        },
        {
            name: 'Cudgel',
            description: ' d4 damage',
            tags: ['weapon', 'melee'],
            dice: Dice.d4,
            exp: true,
            value: 20,
        },
        {
            name: 'Knife',
            description: ' d4 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            roll: 4,
            dice: Dice.d4,
            value: 10,
        },
        {
            name: 'Sling',
            description:
                '  d4 damage, with an unlimited amount of fist-sized rocks',
            tags: ['weapon', 'ranged'],
            exp: false,
            dice: Dice.d4,
            value: 8,
        },
        {
            name: 'Sickle',
            description: ' d4 damage',
            tags: ['weapon', 'melee'],
            dice: Dice.d4,
            exp: true,
            value: 15,
        },
        {
            name: 'Warhammer',
            description: ' d6 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            dice: Dice.d6,
            roll: 5,
            value: 30,
        },
        {
            name: 'Club',
            description: ' d6 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            dice: Dice.d6,
            value: 10,
        },
        {
            name: 'Sword',
            description: ' d6 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            roll: 6,
            dice: Dice.d6,
            value: 30,
        },
        {
            name: 'Handaxe',
            description: ' d6 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            dice: Dice.d6,
            value: 15,
        },
        {
            name: 'Mace',
            description: ' d6 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            dice: Dice.d6,
            value: 25,
        },
        {
            name: 'Spear',
            description: ' d6 damage',
            tags: ['weapon', 'melee'],
            exp: true,
            dice: Dice.d6,
            value: 15,
        },
        {
            name: 'Bow',
            description: ' d6 damage',
            amount: { min: 0, max: 10 },
            mod: 'presence',
            tags: ['weapon', 'ranged'],
            exp: false,
            dice: Dice.d6,
            roll: 7,
            value: 25,
        },
        {
            name: 'Flail',
            description: ' d8 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            roll: 8,
            dice: Dice.d8,
            value: 35,
        },
        {
            name: 'Battle axe',
            description: ' d8 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            dice: Dice.d8,
            value: 35,
        },
        {
            name: 'Goedendag',
            description: ' d8 damage',
            tags: ['weapon', 'melee'],
            exp: true,
            dice: Dice.d8,
            value: 30,
        },
        {
            name: 'Crossbow',
            description: ' d8 damage',
            amount: { min: 10, max: 10 },
            mod: 'presence',
            tags: ['weapon', 'ranged'],
            roll: 9,
            exp: false,
            dice: Dice.d8,
            value: 40,
        },
        {
            name: 'Zweihander',
            description: ' d10 damage',
            tags: ['weapon', 'melee'],
            roll: 10,
            exp: false,
            dice: Dice.d10,
            value: 60,
        },
        {
            name: 'Meat cleaver',
            description: ' d4 damage',
            tags: ['tool', 'metal', 'weapon'],
            exp: false,
            dice: Dice.d4,
            value: 15,
        },
        {
            name: 'Shield',
            description:
                ' (-1 HP damage or have the shield break to ignore one attack)',
            tags: ['shield'],
            dice: Dice.d4,
            exp: false,
            value: 20,
        },
        {
            name: 'Crowbar',
            description: ' d4 damage',
            tags: ['tool', 'metal', 'weapon'],
            dice: Dice.d4,
            exp: false,
            value: 8,
        },
        {
            name: 'Caltrops',
            description: ' d4 damage + infection on 1 in 6',
            tags: ['trap', 'metal'],
            dice: Dice.d4,
            exp: false,
            value: 7,
        },
        {
            name: 'Hammer',
            description: ' d4 damage',
            tags: ['tool', 'metal', 'weapon'],
            dice: Dice.d4,
            exp: false,
            value: 8,
        },
    ],
    equipment: [
        {
            name: 'Backpack',
            description: 'for 7 normal-sized items',
            tags: ['carry'],
            exp: false,
            value: 6,
        },
        {
            name: 'Sack',
            description: 'for 10 normal-sized items',
            tags: ['carry'],
            exp: false,
            value: 3,
        },
        {
            name: 'Small wagon',
            description:
                'can be replaced for a backpack or sack at character creation',
            tags: ['carry'],
            exp: false,
            value: 25,
        },
        {
            name: 'Donkey',
            description:
                'can be replaced for a small wagon, backpack or sack at character creation',
            tags: ['carry'],
            exp: false,
            value: 10,
        },
        {
            name: 'Rope',
            description: ', 30 feet',
            tags: ['tool'],
            exp: false,
            value: 4,
        },
        {
            name: 'Blanket',
            tags: ['camping'],
            description: '',
            exp: false,
            value: 4,
        },
        {
            name: 'Torches',
            amount: { min: 4, max: 4 },
            mod: 'presence',
            tags: ['tool', 'lighting', 'consumable'],
            description: '',
            value: 2,
            exp: false,
        },
        {
            name: 'Lantern',
            description: ' with oil',
            amount: { min: 6, max: 6 },
            mod: 'presence',
            tags: ['tool', 'metal', 'lighting', 'consumable'],
            value: 10,
            exp: false,
        },
        {
            name: 'Magnesium strip',
            tags: ['tool', 'consumable'],
            description: '',
            exp: false,
            value: 4,
        },
        {
            name: 'Firesteel',
            tags: ['tool', 'metal'],
            description: '',
            exp: false,
            value: 4,
        },
        {
            name: 'Chewing tobacco',
            description: '',
            amount: { min: 1, max: 6 },
            tags: ['consumable'],
            value: 1,
            exp: false,
        },
        {
            name: 'Palms Open the Southern Gate',
            description:
                ' A ball of fire hits d2 creatures dealing d8 damage per creature',
            tags: ['scroll', 'unclean'],
            roll: 1,
            value: 50,
            exp: false,
        },
        {
            name: 'Tongue of Eris',
            description:
                ' A creature of your choice is confused for 10 minutes',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 2,
            value: 50,
        },
        {
            name: 'Te-le-kin-esis',
            description: ' Move an object up 1d10 feet for d6 minutes',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 3,
            value: 50,
        },
        {
            name: 'Lucy-Fires Levitation',
            description: ' Hover for Presence + d10 rounds',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 4,
            value: 50,
        },
        {
            name: 'Daemon of Capillaries',
            description:
                ' One creature suffocates for d6 rounds, losing d4 HP per round',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 5,
            value: 50,
        },
        {
            name: 'Nine Violet Signs Unknot the Storm',
            description: ' Produce d2 lightning bolts dealing d6 damage each',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 6,
            value: 50,
        },
        {
            name: 'Metzhuotl Blind Your Eye',
            description:
                ' A creature becomes invisible for d6 rounds or until it is damaged, attacking/defending with DR6',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 7,
            value: 50,
        },
        {
            name: 'Foul Psychopomp',
            description: ' Summon (d6): 1–3 d4 skeletons, 4–6 d4 zombies',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 8,
            value: 50,
        },
        {
            name: 'Eyelid Blinds the Mind',
            description:
                ' d4 creatures fall asleep for one hour unless they succeed a DR14 test',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 9,
            value: 50,
        },
        {
            name: 'Death',
            description:
                ' All creatures within 30 feet lose a total of 4d10 HP',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 10,
            value: 50,
        },
        {
            name: 'Sharp needle',
            tags: ['tool'],
            description: '',
            exp: false,
            value: 3,
        },
        {
            name: 'A bottle of salt',
            tags: ['consumable', 'tool'],
            description: '',
            exp: true,
            value: 3,
        },
        {
            name: 'Wooden crucifix',
            tags: ['symbol'],
            description: '',
            exp: false,
            value: 9,
        },
        {
            name: 'Sticks of chalk',
            amount: { min: 1, max: 6 },
            tags: ['consumable', 'tool'],
            description: '',
            exp: false,
            value: 1,
        },
        {
            name: 'Medicine chest',
            description: 'stops bleeding/infection and heals d6 HP',
            amount: { min: 4, max: 4 },
            mod: 'presence',
            tags: ['consumable', 'tool', 'healing'],
            exp: false,
            value: 15,
        },
        {
            name: 'Metal file and lockpicks',
            tags: ['tool', 'metal'],
            description: '',
            exp: false,
            value: 5,
        },
        {
            name: 'Manacles',
            tags: ['tool', 'metal'],
            description: '',
            value: 10,
            exp: false,
        },
        {
            name: 'Bear trap',
            description: ' (DR14 to spot, d8 damage)',
            tags: ['weapon', 'trap', 'metal'],
            exp: false,
            value: 20,
        },
        {
            name: 'Bomb',
            description: ' (sealed bottle, d10 damage)',
            tags: ['weapon', 'explosive', 'consumable'],
            value: 40,
            exp: true,
        },
        {
            name: 'A bottle of red poison',
            description: 'Toughness DR12 or d10 damage',
            amount: { min: 1, max: 4 },
            tags: ['consumable', 'poison'],
            exp: false,
            value: 20,
        },
        {
            name: 'A bottle of black poison',
            description: 'Toughness DR14 or d6 damage + blind for one hour',
            amount: { min: 1, max: 4 },
            tags: ['consumable', 'poison'],
            exp: false,
            value: 20,
        },
        {
            name: 'Silver crucifix',
            tags: ['symbol', 'metal'],
            description: '',
            exp: false,
            value: 60,
        },
        {
            name: 'Life elixir',
            description: 'heals d6 HP and removes infection',
            amount: { min: 1, max: 4 },
            tags: ['healing', 'consumable'],
            value: 15,
            exp: false,
        },
        {
            name: 'Grace of a Dead Saint',
            description: ' d2 creatures regain d10 HP each',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 1,
        },
        {
            name: 'Grace for a Sinner',
            description:
                ' A creature of your choice gets +d6 on one roll (damage, test etc.)',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 2,
        },
        {
            name: 'Whispers Pass the Gate',
            description: ' Ask three questions to a deceased creature',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 3,
        },
        {
            name: 'Aegis of Sorrow',
            description:
                ' A creature of your choice gains 2d6 extra HP for 10 rounds',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 4,
        },
        {
            name: 'Unmet Fate',
            description:
                ' One creature, dead for no more than a week, is awakened with terrible memories',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 5,
        },
        {
            name: 'Bestial Speech',
            description: ' You may speak with animals for d20 minutes',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 6,
        },
        {
            name: "False Dawn Night's Chariot",
            description: ' Light or pitch black for 3d10 minutes',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 7,
        },
        {
            name: 'Hermetic Step',
            description: ' You find all traps in your path for 2d10 minutes',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 8,
        },
        {
            name: "Roskoe's Consuming Glare",
            description: ' d4 creatures lose d8 HP each',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 9,
        },
        {
            name: 'Enochian Syntax',
            description: ' One creature blindly obeys a single command',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 10,
        },
        {
            name: 'Small but vicious dog',
            description: ' ({hp} HP, bite d4, only obeys you)',
            hp: { min: 1, max: 6, mod: 2 },
            tags: ['animal'],
            exp: false,
            value: 25,
        },
        {
            name: 'Monkeys that ignore but love you',
            description: '2 HP, punch/bite d4',
            amount: { min: 1, max: 4 },
            hp: { min: 1, max: 4, mod: 2 },
            tags: ['animal'],
            exp: false,
            value: 15,
        },
        {
            name: 'Exquisite perfume',
            description: ' worth 25s',
            tags: ['luxury', 'consumable'],
            exp: false,
            value: 25,
        },
        {
            name: 'Mirror',
            description: ', worth 15s',
            tags: ['luxury', 'metal'],
            exp: false,
            value: 15,
        },
        {
            name: 'Toolbox',
            description: ' 10 nails, tongs, hammer, small saw, and drill',
            tags: ['tool', 'metal'],
            exp: false,
            value: 20,
        },
        {
            name: 'Heavy chain',
            description: ' 15 feet',
            tags: ['tool', 'metal'],
            exp: false,
            value: 10,
        },
        {
            name: 'Scissors',
            tags: ['tool', 'metal'],
            description: '',
            exp: false,
            value: 9,
        },
        {
            name: 'Grappling hook',
            tags: ['tool', 'metal'],
            description: '',
            exp: false,
            value: 12,
        },
        {
            name: 'Lard',
            description: ' (may function as 5 meals in a pinch)',
            tags: ['food', 'consumable'],
            exp: false,
            value: 5,
        },
        {
            name: 'Noose',
            tags: ['tool'],
            description: '',
            exp: false,
            value: 5,
        },
        {
            name: 'Tent',
            tags: ['camping'],
            description: '',
            exp: false,
            value: 12,
        },
    ],
    tales: [
        {
            name: 'Pursued for manslaughter. There is a bounty.',
            items: [],
            exp: false,
            roll: 1,
        },
        {
            name: 'In massive debt. The debt is being traded to successively more ruthless groups.',
            items: [],
            exp: false,
            roll: 2,
        },
        {
            name: 'You have a rare, sought after item.',
            items: [],
            exp: false,
            roll: 3,
        },
        {
            name: 'You have a cursed never-healing wound.',
            items: [],
            exp: false,
            roll: 4,
        },
        {
            name: 'Had an illegal, immoral and secret affair with a member of the royal family. You have proof.',
            items: [],
            exp: false,
            roll: 5,
        },
        {
            name: 'Escaped cult member. Terrified and paranoid. Other cultists are everywhere.',
            items: [],
            exp: false,
            roll: 6,
        },
        {
            name: 'An identity thief who recently killed and replaced this person.',
            items: [],
            exp: false,
            roll: 7,
        },
        {
            name: 'Banished and disowned for unspecified deeds. Can never go home.',
            items: [],
            exp: false,
            roll: 8,
        },
        {
            name: 'Deserted military after witnessing a massacre, bounty on head. Hunted by former friends.',
            items: [],
            exp: false,
            roll: 9,
        },
        {
            name: 'Very recently murdered a close relative. Very recently.',
            items: [],
            exp: false,
            roll: 10,
        },
        {
            name: 'A puzzle cube has been calibrated incorrectly (or has it?), awakening a slumbering abomination.',
            items: [],
            exp: false,
            roll: 11,
        },
        {
            name: 'Evil creatures love the scent of your spoor and are drawn to it, bringing disaster in your wake.',
            items: [],
            exp: false,
            roll: 12,
        },
        {
            name: 'A battle wound left a shard of metal slowly inching closer to your heart. Every day there is a 2% chance it reaches it.',
            items: [],
            exp: false,
            roll: 13,
        },
        {
            name: 'Violence forced you into the wilderness. You think waving trees are whispering. You talk to, scream at, attack trees.',
            items: [],
            exp: false,
            roll: 14,
        },
        {
            name: 'Cursed to share the nightmares of others, you sleep far, far away.',
            items: [],
            exp: false,
            roll: 15,
        },
        {
            name: 'At permanent war with all corvids. No contact without some violence. You carry a sling.',
            items: [
                {
                    name: 'Sling',
                    description:
                        '  d4 damage, with an unlimited amount of fist-sized rocks',
                    tags: ['weapon', 'range'],
                    exp: false,
                    value: 8,
                },
            ],
            exp: false,
            roll: 16,
        },
        {
            name: 'After dreaming of an underground temple to a forgotten god you understand the songs of insects and worms.',
            items: [],
            exp: false,
            roll: 17,
        },
        {
            name: 'Being tracked and observed by a golem after an agreement which you know has been wiped from your mind.',
            items: [],
            exp: false,
            roll: 18,
        },
        {
            name: "'Burn or be burned' is the fate you accept.",
            items: [],
            exp: false,
            roll: 19,
        },
        {
            name: "Your flesh heals twice as fast, but your companions twice as slow. You see a many-eyed 'guardian angel'.",
            items: [],
            exp: false,
            roll: 20,
        },
    ],
    habits: [
        {
            name: 'Obsessively collects small sharp stones.',
            items: [
                {
                    name: 'Sackcloth bag',
                    description: 'filled with sharp stones',
                    amount: { min: 0, max: 66 },
                    tags: ['habit-item'],
                    exp: false,
                    value: 0,
                },
            ],
            exp: false,
            roll: 1,
        },
        {
            name: "Won't use a blade without testing it on your own flesh. Arms knitted with scars.",
            items: [],
            exp: false,
            roll: 2,
        },
        {
            name: "Can't stop drinking once you start.",
            items: [],
            exp: false,
            roll: 3,
        },
        {
            name: 'Gambling addict. Must bet every day. If you lose, raise and bet again.',
            items: [],
            exp: false,
            roll: 4,
        },
        {
            name: 'Cannot tolerate criticism of any kind. Results in rage and weeping.',
            items: [],
            exp: false,
            roll: 5,
        },
        {
            name: 'Unable to get to the point. You have never actually finished a story.',
            items: [],
            exp: false,
            roll: 6,
        },
        {
            name: 'Best friend is a skull. Carry it with you, tell it everything, you trust no one more.',
            items: [
                {
                    name: 'Skull',
                    description: ', a trusted friend',
                    tags: ['useless'],
                    exp: false,
                    value: 0,
                },
            ],
            exp: false,
            roll: 7,
        },
        {
            name: 'You pick your nose so deep it bleeds.',
            items: [],
            exp: false,
            roll: 8,
        },
        {
            name: 'Laughs hysterically at your own jokes which you then explain in detail.',
            items: [],
            exp: false,
            roll: 9,
        },
        {
            name: 'A nihilist. You insist on telling everyone you are a nihilist and explaining why.',
            items: [],
            exp: false,
            roll: 10,
        },
        { name: 'Inveterate bug eater.', items: [], exp: false, roll: 11 },
        {
            name: 'Stress response is aestethic display. The worse things get the fancier you need to be.',
            items: [],
            exp: false,
            roll: 12,
        },
        {
            name: 'Permanent phlegm deposit in throat. Continuously coughs, snorts, spits and swallows.',
            items: [],
            exp: false,
            roll: 13,
        },
        { name: 'Pyromaniac.', items: [], exp: false, roll: 14 },
        {
            name: 'Consistently loses important items and forgets vital facts.',
            items: [],
            exp: false,
            roll: 15,
        },
        {
            name: 'Insecure shit-stirrer. Will talk about whoever just left the room.',
            items: [],
            exp: false,
            roll: 16,
        },
        { name: 'You stutter when lying.', items: [], exp: false, roll: 17 },
        {
            name: 'You giggle insanely at the worst possible times.',
            items: [],
            exp: false,
            roll: 18,
        },
        {
            name: 'You whistle while trying to hide. You will deny this. Whistle when 5, 7, 9, 11, or 13 is rolled on a d20.',
            items: [],
            exp: false,
            roll: 19,
        },
        {
            name: 'You make jewelry from the teeth of the dead, if this can be considered a bad habit.',
            items: [
                {
                    name: 'String necklace',
                    description: 'most of the teeth a mismatched...',
                    tags: ['useless'],
                    exp: false,
                    value: 0,
                },
            ],
            exp: false,
            roll: 20,
        },
    ],
    traits: [
        'endlessly aggravated',
        'inferiority complex ridden',
        'authority denying',
        'loud mouth',
        'cruel',
        'egocentric',
        'nihilistic',
        'prone to substance abuse',
        'conflicted',
        'shrewd',
        'vindictive',
        'cowardly',
        'lazy',
        'suspicious',
        'ruthless',
        'constantly worried',
        'very bitter',
        'deceitful',
        'wasteful',
        'arrogant',
    ],
    body: [
        'Has a staring manic gaze',
        'Is covered in (for some) blasphemous tattoos',
        'Has a rotting face (wears a mask)',
        'Is missing 3 toes, is limping',
        'Looks starved: gaunt and pale',
        'One hand is replaced with a rusting hook',
        'Has decaying teeth',
        'Is hauntingly beautiful, unnervingly clean',
        'Has hands caked with sores',
        'Has cataract and its slowly but surely spreading to both eyes',
        'Has long tangled hair, at least one cockroach is in residence',
        'Has broken crushed ears',
        'Is juddering and stuttering from nerve damage or stress',
        'Is corpulent, ravenous, drooling',
        'In one hand misses a thumb and index finger, grips like a lobster',
        "Has a red, swollen alcoholic's nose",
        'Has resting maniac face, making friends is hard',
        "Has chronic athlete's foot",
        'Was recently slashed and stinking eye is covered with a patch',
        'Has cracked black nails, probably about to drop off',
    ],
};
