import { GameData } from '../models';
import { Dice } from '../utils/rollDie';

export const data: GameData = {
    armors: [
        {
            name: 'Fur armor',
            description: ' -d2 damage, tier 1',
            tags: ['armor', 'light-armor'],
            exp: false,
            maxTier: 1,
            dice: [Dice.d2],
            roll: 2,
            value: 20,
        },
        {
            name: 'Padded cloth armor',
            description: ' -d2 damage, tier 1',
            tags: ['armor', 'light-armor'],
            exp: false,
            maxTier: 1,
            roll: 2,
            dice: [Dice.d2],
            value: 20,
        },
        {
            name: 'Leather armor',
            description: ' -d2 damage, tier 1',
            tags: ['armor', 'light-armor'],
            exp: false,
            maxTier: 1,
            roll: 2,
            dice: [Dice.d2],
            value: 20,
        },
        {
            name: 'Scale armor',
            description:
                ' -d4 damage, tier 2, DR +2 on Agility tests including defence',
            tags: ['armor', 'medium-armor', 'metal'],
            exp: false,
            maxTier: 2,
            roll: 3,
            dice: [Dice.d4],
            value: 100,
            modifiers: [
                {
                    statistic: 'agility',
                    value: -2,
                    source: 'Scale armor',
                },
            ],
        },
        {
            name: 'Mail armor',
            description:
                ' -d4 damage, tier 2, DR +2 on Agility tests including defence',
            tags: ['armor', 'medium-armor', 'metal'],
            exp: false,
            maxTier: 2,
            roll: 3,
            dice: [Dice.d4],
            value: 100,
            modifiers: [
                {
                    statistic: 'agility',
                    value: -2,
                    source: 'Mail armor',
                },
            ],
        },
        {
            name: 'Splint armor',
            description:
                ' -d6 damage, tier 3, DR +4 on Agility tests, defence is DR +2',
            tags: ['armor', 'heavy-armor', 'metal'],
            exp: false,
            maxTier: 3,
            roll: 4,
            dice: [Dice.d6],
            value: 200,
            modifiers: [
                {
                    statistic: 'agility',
                    value: -4,
                    source: 'Splint armor',
                    exclude: ['defence', 'buff', 'item'],
                },
                {
                    statistic: 'agility',
                    value: -2,
                    source: 'Splint armor',
                    exclude: [
                        'ability',
                        'test',
                        'melee',
                        'ranged',
                        'cast',
                        'heal',
                        'buff',
                    ],
                },
            ],
        },
        {
            name: 'Plate armor',
            description:
                ' -d6 damage, tier 3, DR +4 on Agility tests, defence is DR +2',
            tags: ['armor', 'heavy-armor', 'metal'],
            exp: false,
            maxTier: 3,
            roll: 4,
            dice: [Dice.d6],
            value: 200,
            modifiers: [
                {
                    statistic: 'agility',
                    value: -4,
                    source: 'Plate armor',
                    exclude: ['defence', 'buff'],
                },
                {
                    statistic: 'agility',
                    value: -2,
                    source: 'Plate armor',
                    exclude: [
                        'ability',
                        'test',
                        'melee',
                        'ranged',
                        'cast',
                        'heal',
                        'buff',
                    ],
                },
            ],
        },
    ],
    weapons: [
        {
            name: 'The Snake-Skin Gift',
            description:
                'An expensive sandalwood box bound in snakeskin. It contains a seemingly ordinary dagger, wrapped in silk. d4 damage',
            exp: false,
            tags: ['weapon', 'special', 'melee'],
            value: 0,
            dice: [Dice.d4],
            effectDie: Dice.d4,
            effect: {
                1: {
                    text: 'The target dies immediately of deadly poison weeping from the blade',
                },
                2: { text: 'No additional effect' },
                3: { text: 'No additional effect' },
                4: { text: 'No additional effect' },
            },
        },
        {
            name: 'The Blade of your Ancestors',
            description:
                'This magnificent and clearly magical talking sword is foppish, unreliable and quietly despises you. It taunts your failures and, is continually disappointed.',
            tags: ['weapon', 'melee', 'special'],
            dice: [Dice.d6],
            exp: false,
            value: 0,
            effectDie: Dice.d6,
            damageModifier: 1,
            effect: {
                1: {
                    text: 'The blade, "accidentally" attacks one of your companions',
                },
                2: { text: 'No additional effect' },
                3: { text: 'No additional effect' },
                4: { text: 'No additional effect' },
                5: { text: 'No additional effect' },
                6: { text: 'No additional effect' },
            },
        },
        {
            name: 'The Brown Scimitar of Galgenbeck',
            description:
                'A stinking sword you pulled from a military shit-ditch. D6 damage.',
            tags: ['weapon', 'melee', 'special'],
            dice: [Dice.d6],
            exp: false,
            value: 0,
            effectDie: Dice.d6,
            effect: {
                1: {
                    text: 'Your enemy is struck with a potent sepsis, he will most likely die in 10 mins',
                },
                2: { text: 'No additional effect' },
                3: { text: 'No additional effect' },
                4: { text: 'No additional effect' },
                5: { text: 'No additional effect' },
                6: { text: 'No additional effect' },
            },
        },
        {
            name: `Old Sig\xfbrd's Sling`,
            description: `Sig\xfbrd was the strongest man whose throat you ever gnawed. Woven from his long grey hair, this sling has never failed you. 2d4 damage`,
            tags: ['weapon', 'melee', 'special'],
            dice: [Dice.d4, Dice.d4],
            exp: false,
            value: 0,
            ammo: { type: 'Infinite', startWith: 999 },
        },
        {
            name: 'Femur',
            description: 'd4 damage',
            tags: ['weapon', 'melee'],
            dice: [Dice.d4],
            roll: 1,
            exp: false,
            value: 0,
        },
        {
            name: "The Shoe of Death's Horse",
            description:
                'It looks normal but since finding it in an obscure crypt you are convinced this shoe came from the horse of Death himself. D4 damage.',
            tags: ['weapon', 'range', 'special'],
            dice: [Dice.d4],
            effectDie: Dice.d6,
            effect: {
                1: {
                    text: 'The shoe smashes the skull, instantly killing small-to-medium sized creatures.',
                },
                2: { text: 'No additional effect' },
                3: { text: 'No additional effect' },
                4: { text: 'No additional effect' },
                5: { text: 'No additional effect' },
                6: { text: 'No additional effect' },
            },
            exp: false,
            value: 0,
        },
        {
            name: 'Staff',
            description: ' d4 damage',
            tags: ['weapon', 'melee'],
            dice: [Dice.d4],
            roll: 2,
            exp: false,
            value: 5,
        },
        {
            name: 'Whip',
            description: ' d2 damage',
            tags: ['weapon', 'melee'],
            dice: [Dice.d2],
            exp: false,
            value: 5,
        },
        {
            name: 'Shortsword',
            description: ' d4 damage',
            tags: ['weapon', 'melee'],
            dice: [Dice.d4],
            exp: false,
            roll: 3,
            value: 20,
        },
        {
            name: 'Cudgel',
            description: ' d4 damage',
            tags: ['weapon', 'melee'],
            dice: [Dice.d4],
            exp: true,
            value: 20,
        },
        {
            name: 'Knife',
            description: ' d4 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            roll: 4,
            dice: [Dice.d4],
            value: 10,
        },
        {
            name: 'Sling',
            description:
                '  d4 damage, with an unlimited amount of fist-sized rocks',
            tags: ['weapon', 'ranged'],
            exp: false,
            dice: [Dice.d4],
            value: 8,
        },
        {
            name: 'Sickle',
            description: ' d4 damage',
            tags: ['weapon', 'melee'],
            dice: [Dice.d4],
            exp: true,
            value: 15,
        },
        {
            name: 'Warhammer',
            description: ' d6 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            dice: [Dice.d6],
            roll: 5,
            value: 30,
        },
        {
            name: 'Club',
            description: ' d6 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            dice: [Dice.d6],
            value: 10,
        },
        {
            name: 'Sword',
            description: ' d6 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            roll: 6,
            dice: [Dice.d6],
            value: 30,
        },
        {
            name: 'Handaxe',
            description: ' d6 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            dice: [Dice.d6],
            value: 15,
        },
        {
            name: 'Mace',
            description: ' d6 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            dice: [Dice.d6],
            value: 25,
        },
        {
            name: 'Spear',
            description: ' d6 damage',
            tags: ['weapon', 'melee'],
            exp: true,
            dice: [Dice.d6],
            value: 15,
        },
        {
            name: 'Bow',
            description: ' d6 damage',
            ammo: { type: 'Arrow', startWith: 10 },
            mod: 'presence',
            tags: ['weapon', 'ranged'],
            exp: false,
            dice: [Dice.d6],
            roll: 7,
            value: 25,
        },
        {
            name: 'Flail',
            description: ' d8 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            roll: 8,
            dice: [Dice.d8],
            value: 35,
        },
        {
            name: 'Battle axe',
            description: ' d8 damage',
            tags: ['weapon', 'melee'],
            exp: false,
            dice: [Dice.d8],
            value: 35,
        },
        {
            name: 'Goedendag',
            description: ' d8 damage',
            tags: ['weapon', 'melee'],
            exp: true,
            dice: [Dice.d8],
            value: 30,
        },
        {
            name: 'Crossbow',
            description: ' d8 damage',
            ammo: { type: 'Bolt', startWith: 10 },
            mod: 'presence',
            tags: ['weapon', 'ranged'],
            roll: 9,
            exp: false,
            dice: [Dice.d8],
            value: 40,
        },
        {
            name: 'Zweihander',
            description: ' d10 damage',
            tags: ['weapon', 'melee'],
            roll: 10,
            exp: false,
            dice: [Dice.d10],
            value: 60,
        },
        {
            name: 'Meat cleaver',
            description: ' d4 damage',
            tags: ['tool', 'metal', 'weapon'],
            exp: false,
            dice: [Dice.d4],
            value: 15,
        },
        {
            name: 'Shield',
            description:
                ' (-1 HP damage or have the shield break to ignore one attack)',
            tags: ['shield'],
            dice: [Dice.d4],
            exp: false,
            value: 20,
        },
        {
            name: 'Crowbar',
            description: ' d4 damage',
            tags: ['tool', 'metal', 'weapon'],
            dice: [Dice.d4],
            exp: false,
            value: 8,
        },
        {
            name: 'Caltrops',
            description: ' d4 damage + infection on 1 in 6',
            tags: ['trap', 'metal'],
            dice: [Dice.d4],
            exp: false,
            value: 7,
        },
        {
            name: 'Hammer',
            description: ' d4 damage',
            tags: ['tool', 'metal', 'weapon'],
            dice: [Dice.d4],
            exp: false,
            value: 8,
        },
    ],
    equipment: [
        {
            name: 'Backpack',
            description: 'for 7 normal-sized items',
            tags: ['carry'],
            exp: false,
            value: 6,
        },
        {
            name: 'Sack',
            description: 'for 10 normal-sized items',
            tags: ['carry'],
            exp: false,
            value: 3,
        },
        {
            name: 'Small wagon',
            description: "It's a wagon, you can put stuff in",
            tags: ['carry'],
            exp: false,
            value: 25,
        },
        {
            name: 'Donkey',
            description: 'Mostly ignores you',
            tags: ['carry'],
            exp: false,
            value: 10,
        },
        {
            name: 'Rope',
            description: '30 feet',
            tags: ['tool'],
            exp: false,
            value: 4,
        },
        {
            name: 'Blanket',
            tags: ['camping'],
            description: '',
            exp: false,
            value: 4,
        },
        {
            name: 'Torches',
            ammo: { type: 'Torch', startWith: 6 },
            mod: 'presence',
            tags: ['tool', 'lighting', 'consumable'],
            description: '',
            value: 2,
            exp: false,
        },
        {
            name: 'Lantern',
            description: ' with oil',
            ammo: { type: 'Oil', startWith: 6 },
            mod: 'presence',
            tags: ['tool', 'metal', 'lighting', 'consumable'],
            value: 10,
            exp: false,
        },
        {
            name: 'Magnesium strip',
            tags: ['tool', 'consumable'],
            description: '',
            exp: false,
            value: 4,
        },
        {
            name: 'Firesteel',
            tags: ['tool', 'metal'],
            description: '',
            exp: false,
            value: 4,
        },
        {
            name: 'Chewing tobacco',
            description: '',
            multiple: 4,
            tags: ['consumable'],
            value: 1,
            exp: false,
        },
        {
            name: 'Palms Open the Southern Gate',
            description:
                ' A ball of fire hits d2 creatures dealing d8 damage per creature',
            tags: ['scroll', 'unclean'],
            roll: 1,
            value: 50,
            exp: false,
        },
        {
            name: 'Tongue of Eris',
            description:
                ' A creature of your choice is confused for 10 minutes',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 2,
            value: 50,
        },
        {
            name: 'Te-le-kin-esis',
            description: ' Move an object up 1d10 feet for d6 minutes',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 3,
            value: 50,
        },
        {
            name: 'Lucy-Fires Levitation',
            description: ' Hover for Presence + d10 rounds',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 4,
            value: 50,
        },
        {
            name: 'Daemon of Capillaries',
            description:
                ' One creature suffocates for d6 rounds, losing d4 HP per round',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 5,
            value: 50,
        },
        {
            name: 'Nine Violet Signs Unknot the Storm',
            description: ' Produce d2 lightning bolts dealing d6 damage each',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 6,
            value: 50,
        },
        {
            name: 'Metzhuotl Blind Your Eye',
            description:
                ' A creature becomes invisible for d6 rounds or until it is damaged, attacking/defending with DR6',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 7,
            value: 50,
        },
        {
            name: 'Foul Psychopomp',
            description: ' Summon (d6): 1–3 d4 skeletons, 4–6 d4 zombies',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 8,
            value: 50,
        },
        {
            name: 'Eyelid Blinds the Mind',
            description:
                ' d4 creatures fall asleep for one hour unless they succeed a DR14 test',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 9,
            value: 50,
        },
        {
            name: 'Death',
            description:
                ' All creatures within 30 feet lose a total of 4d10 HP',
            tags: ['scroll', 'unclean'],
            exp: false,
            roll: 10,
            value: 50,
        },
        {
            name: 'Sharp needle',
            tags: ['tool'],
            description: '',
            exp: false,
            value: 3,
        },
        {
            name: 'A bottle of salt',
            tags: ['consumable', 'tool'],
            description: '',
            exp: true,
            value: 3,
        },
        {
            name: 'Wooden crucifix',
            tags: ['symbol'],
            description: '',
            exp: false,
            value: 9,
        },
        {
            name: 'Stick of chalk',
            multiple: 4,
            tags: ['consumable', 'tool'],
            description: '',
            exp: false,
            value: 1,
        },
        {
            name: 'Medicine chest',
            description: 'stops bleeding/infection and heals d6 HP',
            mod: 'presence',
            tags: ['consumable', 'tool', 'healing'],
            exp: false,
            value: 15,
            use: {
                value: Dice.d6,
                type: 'heal',
            },
            multiple: 2,
        },
        {
            name: 'Metal file and lockpicks',
            tags: ['tool', 'metal'],
            description: '',
            exp: false,
            value: 5,
        },
        {
            name: 'Manacles',
            tags: ['tool', 'metal'],
            description: '',
            value: 10,
            exp: false,
        },
        {
            name: 'Bear trap',
            description: ' (DR14 to spot, d8 damage)',
            tags: ['trap', 'metal'],
            exp: false,
            value: 20,
        },
        {
            name: 'Bomb',
            description: ' (sealed bottle, d10 damage)',
            tags: ['weapon', 'explosive', 'consumable', 'ranged'],
            dice: [Dice.d10],
            value: 40,
            exp: true,
        },
        {
            name: 'A bottle of red poison',
            description: 'Toughness DR12 or d10 damage',
            tags: ['consumable', 'poison'],
            exp: false,
            use: { type: 'item', value: 0 },
            value: 20,
        },
        {
            name: 'A bottle of black poison',
            description: 'Toughness DR14 or d6 damage + blind for one hour',
            tags: ['consumable', 'poison'],
            exp: false,
            use: { type: 'item', value: 0 },
            value: 20,
        },
        {
            name: 'Silver crucifix',
            tags: ['symbol', 'metal'],
            description: '',
            exp: false,
            value: 60,
        },
        {
            name: 'Life elixir',
            description: 'heals d6 HP and removes infection',
            tags: ['healing', 'consumable'],
            value: 15,
            exp: false,
            use: {
                value: Dice.d6,
                type: 'heal',
            },
        },
        {
            name: 'Grace of a Dead Saint',
            description: ' d2 creatures regain d10 HP each',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 1,
        },
        {
            name: 'Grace for a Sinner',
            description:
                ' A creature of your choice gets +d6 on one roll (damage, test etc.)',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 2,
        },
        {
            name: 'Whispers Pass the Gate',
            description: ' Ask three questions to a deceased creature',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 3,
        },
        {
            name: 'Aegis of Sorrow',
            description:
                ' A creature of your choice gains 2d6 extra HP for 10 rounds',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 4,
        },
        {
            name: 'Unmet Fate',
            description:
                ' One creature, dead for no more than a week, is awakened with terrible memories',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 5,
        },
        {
            name: 'Bestial Speech',
            description: ' You may speak with animals for d20 minutes',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 6,
        },
        {
            name: "False Dawn Night's Chariot",
            description: ' Light or pitch black for 3d10 minutes',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 7,
        },
        {
            name: 'Hermetic Step',
            description: ' You find all traps in your path for 2d10 minutes',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 8,
        },
        {
            name: "Roskoe's Consuming Glare",
            description: ' d4 creatures lose d8 HP each',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 9,
        },
        {
            name: 'Enochian Syntax',
            description: ' One creature blindly obeys a single command',
            tags: ['scroll', 'sacred'],
            exp: false,
            value: 50,
            roll: 10,
        },
        {
            name: 'Exquisite perfume',
            description: ' worth 25s',
            tags: ['luxury', 'consumable'],
            exp: false,
            value: 25,
        },
        {
            name: 'Mirror',
            description: ', worth 15s',
            tags: ['luxury', 'metal'],
            exp: false,
            value: 15,
        },
        {
            name: 'Toolbox',
            description: ' 10 nails, tongs, hammer, small saw, and drill',
            tags: ['tool', 'metal'],
            exp: false,
            value: 20,
        },
        {
            name: 'Heavy chain',
            description: ' 15 feet',
            tags: ['tool', 'metal'],
            exp: false,
            value: 10,
        },
        {
            name: 'Scissors',
            tags: ['tool', 'metal'],
            description: '',
            exp: false,
            value: 9,
        },
        {
            name: 'Grappling hook',
            tags: ['tool', 'metal'],
            description: '',
            exp: false,
            value: 12,
        },
        {
            name: 'Lard',
            description: ' (may function as 5 meals in a pinch)',
            tags: ['food', 'consumable'],
            exp: false,
            value: 5,
        },
        {
            name: 'Noose',
            tags: ['tool'],
            description: '',
            exp: false,
            value: 5,
        },
        {
            name: 'Tent',
            tags: ['camping'],
            description: '',
            exp: false,
            value: 12,
        },
        {
            name: 'Ezumiel Vapor',
            description:
                'Pass a DR14 test or severe (and arguably fun) hallucinations occur',
            tags: ['consumable'],
            exp: false,
            value: 0,
            use: {
                effectDie: Dice.d4,
                effects: {
                    1: { text: 'Hallucinations last 1 hour' },
                    2: { text: 'Hallucinations last 2 hours' },
                    3: { text: 'Hallucinations last 3 hours' },
                    4: { text: 'Hallucinations last 4 hours' },
                },
                type: 'item',
                value: 0,
            },
        },
        {
            name: 'Southern Frog Stew',
            description:
                'Vomit for some time, pass a DR14 test or you can nothing else',
            tags: ['consumable'],

            exp: false,
            value: 0,
            use: {
                effectDie: Dice.d4,
                effects: {
                    1: { text: 'Vomiting lasts 1 hour' },
                    2: { text: 'Vomiting lasts 2 hours' },
                    3: { text: 'Vomiting lasts 3 hours' },
                    4: { text: 'Vomiting lasts 4 hours' },
                },
                type: 'item',
                value: 0,
            },
        },
        {
            name: 'Elixir Vitalis',
            description:
                'Heals d6 HP and stops infection. Can be habit forming',
            tags: ['consumable'],
            exp: false,
            value: 0,
            use: {
                type: 'item',
                value: Dice.d6,
            },
        },
        {
            name: 'Spider-Owl Soup',
            description: 'See in darkness climb on walls for 30 minutes',
            tags: ['consumable'],
            exp: false,
            value: 0,
            use: {
                type: 'item',
                value: 0,
            },
        },
        {
            name: "Fernor's Philtre",
            description:
                'Translucent oir, must be dabbed right into the eye. Heals infection and gives +2 presence for some time',
            tags: ['consumable'],
            exp: false,
            value: 0,
            use: {
                type: 'buff',
                value: 0,
                effectDie: Dice.d4,
                effects: {
                    1: {
                        text: '+2 presence for 1 hour',
                        statuses: [
                            {
                                statistic: 'presence',
                                value: 2,
                                source: "Fernor's Philtre",
                            },
                        ],
                    },
                    2: {
                        text: '+2 presence for 1 hour',
                        statuses: [
                            {
                                statistic: 'presence',
                                value: 2,
                                source: "Fernor's Philtre",
                            },
                        ],
                    },
                    3: {
                        text: '+2 presence for 3 hours',
                        statuses: [
                            {
                                statistic: 'presence',
                                value: 2,
                                source: "Fernor's Philtre",
                            },
                        ],
                    },
                    4: {
                        text: '+2 presence for 4 hours',
                        statuses: [
                            {
                                statistic: 'presence',
                                value: 2,
                                source: "Fernor's Philtre",
                            },
                        ],
                    },
                },
            },
        },
        {
            name: "Hyphos's Enevating Snuff",
            description:
                'Berserk! Two attacks per round but defend with D14, lasts one fight. Must be snorted, causes sneezing',
            tags: ['consumable'],
            exp: false,
            value: 0,
            use: {
                type: 'buff',
                effectDie: 1,
                value: 0,
                effects: {
                    1: {
                        text: 'You are berserk! Two attack this fight defence is reduced',
                        statuses: [
                            {
                                statistic: 'agility',
                                value: -2,
                                source: 'Hyphos snuff',
                                exclude: [
                                    'ability',
                                    'heal',
                                    'ranged',
                                    'melee',
                                    'cast',
                                ],
                            },
                        ],
                    },
                },
            },
        },
    ],
    pets: [
        {
            name: 'Small but vicious dog',
            description: ' (bite d4, only obeys you)',
            hp: 6,
            tags: ['animal', 'pet'],
            exp: false,
            actionDie: [Dice.d4],
            value: 25,
            actionType: 'melee',
            amount: 1,
        },
        {
            name: 'Monkey',
            description: 'It ignores you but love you 2 HP, punch/bite d4',
            hp: 2,
            tags: ['animal', 'pet'],
            exp: false,
            actionDie: [Dice.d4],
            value: 15,
            actionType: 'melee',
            amount: Dice.d4,
        },
        {
            name: 'Hawk',
            tags: ['pet', 'special'],
            exp: false,
            hp: 8,
            description:
                'Your crafty almost-intelligent hawk is loyal only to you. Even without shared language, you understand its cries as it keeps watch, scouts and swoops to attack foes.',
            actionType: 'melee',
            actionDie: [Dice.d4],
            amount: 1,
        },
        {
            name: 'Ancient Gore-Hound',
            description:
                'Asthmatic, deluded and on its last legs, this wizened creature still has a superb nose and can snif\ufb02e up treasure in the most disgusting debris.\nBecomes frenzied around goblins and berserkers.',
            exp: false,
            hp: 10,
            actionType: 'melee',
            actionDie: [Dice.d6],
            tags: ['pet', 'special'],
            amount: 1,
        },
        {
            name: 'Hamfund the Squire',
            description:
                'This intensely cowardly servant acts only as guardian for the scabbard of the cursed sword Eurekia. Once per combat, if Ham can be found, Eurekia may be drawn (2d6).',
            exp: false,
            hp: 1,
            actionType: 'melee',
            actionDie: [Dice.d6, Dice.d6],
            tags: ['pet', 'special', 'humanoid'],
            amount: 1,
        },
        {
            name: 'Barbarister the Incredible Horse',
            description:
                'Barbarister is magical, inteligent, arrogant and vein \n If you can persuade him to care Barbaister occasionally adds + 2 to Presence tests. \n The horse may be smarter than you and is quite aware of this',
            exp: false,
            hp: 1,
            actionType: 'buff',
            actionDie: [],
            tags: ['pet', 'special'],
            buff: [
                {
                    statistic: 'presence',
                    value: 2,
                    source: 'Barbaristers guidence',
                    exclude: [
                        'melee',
                        'ranged',
                        'cast',
                        'ability',
                        'defence',
                        'buff',
                    ],
                },
            ],

            amount: 1,
        },
        {
            name: '"Poltroon" the Court Jester',
            description:
                "While practically useless, personally irritating and an emotional drain,\nPoltroon's capering actually makes enemies lose their focus in combat. \nFor the first two rounds you and your allies get +2 on attack/defence.",
            actionType: 'buff',
            actionDie: [],
            hp: 1,
            exp: false,
            tags: ['pet', 'special'],
            buff: [
                {
                    statistic: 'agility',
                    value: 2,
                    source: 'Poltroons annoyance',
                    exclude: [
                        'melee',
                        'ranged',
                        'cast',
                        'ability',
                        'test',
                        'heal',
                        'buff',
                    ],
                },
                {
                    statistic: 'strength',
                    value: 2,
                    source: 'Poltroons annoyance',
                    exclude: [
                        'defence',
                        'ranged',
                        'cast',
                        'ability',
                        'test',
                        'heal',
                        'buff',
                    ],
                },
                {
                    statistic: 'presence',
                    value: 2,
                    source: 'Poltroons annoyance',
                    exclude: [
                        'defence',
                        'melee',
                        'cast',
                        'ability',
                        'test',
                        'heal',
                        'buff',
                    ],
                },
            ],
            amount: 1,
        },
    ],
    tales: [
        {
            name: 'Pursued for manslaughter. There is a bounty.',
            items: [],
            exp: false,
            roll: 1,
        },
        {
            name: 'In massive debt. The debt is being traded to successively more ruthless groups.',
            items: [],
            exp: false,
            roll: 2,
        },
        {
            name: 'You have a rare, sought after item.',
            items: [],
            exp: false,
            roll: 3,
        },
        {
            name: 'You have a cursed never-healing wound.',
            items: [],
            exp: false,
            roll: 4,
        },
        {
            name: 'Had an illegal, immoral and secret affair with a member of the royal family. You have proof.',
            items: [],
            exp: false,
            roll: 5,
        },
        {
            name: 'Escaped cult member. Terrified and paranoid. Other cultists are everywhere.',
            items: [],
            exp: false,
            roll: 6,
        },
        {
            name: 'An identity thief who recently killed and replaced this person.',
            items: [],
            exp: false,
            roll: 7,
        },
        {
            name: 'Banished and disowned for unspecified deeds. Can never go home.',
            items: [],
            exp: false,
            roll: 8,
        },
        {
            name: 'Deserted military after witnessing a massacre, bounty on head. Hunted by former friends.',
            items: [],
            exp: false,
            roll: 9,
        },
        {
            name: 'Very recently murdered a close relative. Very recently.',
            items: [],
            exp: false,
            roll: 10,
        },
        {
            name: 'A puzzle cube has been calibrated incorrectly (or has it?), awakening a slumbering abomination.',
            items: [],
            exp: false,
            roll: 11,
        },
        {
            name: 'Evil creatures love the scent of your spoor and are drawn to it, bringing disaster in your wake.',
            items: [],
            exp: false,
            roll: 12,
        },
        {
            name: 'A battle wound left a shard of metal slowly inching closer to your heart. Every day there is a 2% chance it reaches it.',
            items: [],
            exp: false,
            roll: 13,
        },
        {
            name: 'Violence forced you into the wilderness. You think waving trees are whispering. You talk to, scream at, attack trees.',
            items: [],
            exp: false,
            roll: 14,
        },
        {
            name: 'Cursed to share the nightmares of others, you sleep far, far away.',
            items: [],
            exp: false,
            roll: 15,
        },
        {
            name: 'At permanent war with all corvids. No contact without some violence. You carry a sling.',
            items: [
                {
                    name: 'Sling',
                    description:
                        '  d4 damage, with an unlimited amount of fist-sized rocks',
                    tags: ['weapon', 'range'],
                    exp: false,
                    value: 8,
                },
            ],
            exp: false,
            roll: 16,
        },
        {
            name: 'After dreaming of an underground temple to a forgotten god you understand the songs of insects and worms.',
            items: [],
            exp: false,
            roll: 17,
        },
        {
            name: 'Being tracked and observed by a golem after an agreement which you know has been wiped from your mind.',
            items: [],
            exp: false,
            roll: 18,
        },
        {
            name: "'Burn or be burned' is the fate you accept.",
            items: [],
            exp: false,
            roll: 19,
        },
        {
            name: "Your flesh heals twice as fast, but your companions twice as slow. You see a many-eyed 'guardian angel'.",
            items: [],
            exp: false,
            roll: 20,
        },
    ],
    habits: [
        {
            name: 'Obsessively collects small sharp stones.',
            items: [
                {
                    name: 'Sackcloth bag',
                    description: 'filled with sharp stones',
                    ammo: { type: 'Stone', startWith: 66 },
                    tags: ['habit-item'],
                    exp: false,
                    value: 0,
                },
            ],
            exp: false,
            roll: 1,
        },
        {
            name: "Won't use a blade without testing it on your own flesh. Arms knitted with scars.",
            items: [],
            exp: false,
            roll: 2,
        },
        {
            name: "Can't stop drinking once you start.",
            items: [],
            exp: false,
            roll: 3,
        },
        {
            name: 'Gambling addict. Must bet every day. If you lose, raise and bet again.',
            items: [],
            exp: false,
            roll: 4,
        },
        {
            name: 'Cannot tolerate criticism of any kind. Results in rage and weeping.',
            items: [],
            exp: false,
            roll: 5,
        },
        {
            name: 'Unable to get to the point. You have never actually finished a story.',
            items: [],
            exp: false,
            roll: 6,
        },
        {
            name: 'Best friend is a skull. Carry it with you, tell it everything, you trust no one more.',
            items: [
                {
                    name: 'Skull',
                    description: ', a trusted friend',
                    tags: ['useless'],
                    exp: false,
                    value: 0,
                },
            ],
            exp: false,
            roll: 7,
        },
        {
            name: 'You pick your nose so deep it bleeds.',
            items: [],
            exp: false,
            roll: 8,
        },
        {
            name: 'Laughs hysterically at your own jokes which you then explain in detail.',
            items: [],
            exp: false,
            roll: 9,
        },
        {
            name: 'A nihilist. You insist on telling everyone you are a nihilist and explaining why.',
            items: [],
            exp: false,
            roll: 10,
        },
        { name: 'Inveterate bug eater.', items: [], exp: false, roll: 11 },
        {
            name: 'Stress response is aestethic display. The worse things get the fancier you need to be.',
            items: [],
            exp: false,
            roll: 12,
        },
        {
            name: 'Permanent phlegm deposit in throat. Continuously coughs, snorts, spits and swallows.',
            items: [],
            exp: false,
            roll: 13,
        },
        { name: 'Pyromaniac.', items: [], exp: false, roll: 14 },
        {
            name: 'Consistently loses important items and forgets vital facts.',
            items: [],
            exp: false,
            roll: 15,
        },
        {
            name: 'Insecure shit-stirrer. Will talk about whoever just left the room.',
            items: [],
            exp: false,
            roll: 16,
        },
        { name: 'You stutter when lying.', items: [], exp: false, roll: 17 },
        {
            name: 'You giggle insanely at the worst possible times.',
            items: [],
            exp: false,
            roll: 18,
        },
        {
            name: 'You whistle while trying to hide. You will deny this. Whistle when 5, 7, 9, 11, or 13 is rolled on a d20.',
            items: [],
            exp: false,
            roll: 19,
        },
        {
            name: 'You make jewelry from the teeth of the dead, if this can be considered a bad habit.',
            items: [
                {
                    name: 'String necklace',
                    description: 'most of the teeth a mismatched...',
                    tags: ['useless'],
                    exp: false,
                    value: 0,
                },
            ],
            exp: false,
            roll: 20,
        },
    ],
    traits: [
        'endlessly aggravated',
        'inferiority complex ridden',
        'authority denying',
        'loud mouth',
        'cruel',
        'egocentric',
        'nihilistic',
        'prone to substance abuse',
        'conflicted',
        'shrewd',
        'vindictive',
        'cowardly',
        'lazy',
        'suspicious',
        'ruthless',
        'constantly worried',
        'very bitter',
        'deceitful',
        'wasteful',
        'arrogant',
    ],
    body: [
        'Has a staring manic gaze',
        'Is covered in (for some) blasphemous tattoos',
        'Has a rotting face (wears a mask)',
        'Is missing 3 toes, is limping',
        'Looks starved: gaunt and pale',
        'One hand is replaced with a rusting hook',
        'Has decaying teeth',
        'Is hauntingly beautiful, unnervingly clean',
        'Has hands caked with sores',
        'Has cataract and its slowly but surely spreading to both eyes',
        'Has long tangled hair, at least one cockroach is in residence',
        'Has broken crushed ears',
        'Is juddering and stuttering from nerve damage or stress',
        'Is corpulent, ravenous, drooling',
        'In one hand misses a thumb and index finger, grips like a lobster',
        "Has a red, swollen alcoholic's nose",
        'Has resting maniac face, making friends is hard',
        "Has chronic athlete's foot",
        'Was recently slashed and stinking eye is covered with a patch',
        'Has cracked black nails, probably about to drop off',
    ],
};
